title:
  type: text
  perm:
    update: office
startDate:
  type: datetime
  perm:
    update: office
  label: start date
endDate:
  type: datetime
  perm:
    update: office
  label: end date
typeContribution:
  label: Type
  type: typeContribution
  multiple: true
  perm:
    update: office
remarks:
  type: text
  multiple: true
  perm:
    update: office
