perm:
  list:   public
  read:   public
  update: office
  insert: office
  delete: office

title: title

item:
  - package
  - packages

sort:
  - [title, 1]
  - [dateCreated, -1]

fieldOrder: 
  - title
  - startDate
  - endDate
  - typeContribution
  - remarks

fieldSpecs: 
  title:
    perm:
      list: public
      read: public
      update: office
    label: Title
    valType: text
    multiple: false
  startDate:
    perm:
      list: public
      read: public
      update: office
    label: start date
    valType: datetime
    multiple: false
  endDate:
    perm:
      list: public
      read: public
      update: office
    label: end date
    valType: datetime
    multiple: false
  typeContribution:
    perm:
      list: public
      read: public
      update: office
    label: Type
    valType:
      relTable: typeContribution
      allowNew: true
      inactive:
        attributes:
          className: inactive
          data-rh: this value does not belong to the current package
        disabled: false
    multiple: true
  remarks:
    perm:
      list: public
      read: public
      update: office
    label: Remarks
    valType: textarea
    multiple: true

detailOrder:
  - criteria

details:
  criteria:
    table: criteria
    linkField: package
    mode: list
    filtered: true
