site_name: Tech Doc DARIAH contribution tool
site_description: > 
  The technical documentation of the DARIAH Contribution Tool.
  Design, specs, rationales, patterns, diagrams.

site_url: "https://dans-labs.github.io/dariah/" 
site_author: Dirk Roorda

repo_name: Dans-labs/dariah
repo_url: 'https://github.com/dans-labs/dariah/'

theme:
  name: dans
  logo: 'images/inkind_logo.png'
  favicon: 'icons/favicon.ico'
  development: true
  development_label: still in beta
  production_link: ''
  client:
    name: DARIAH
    url: https://www.dariah.eu
    logo: images/dariah.png 
  feature:
    tabs: true

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Dans-labs
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - markdownextradata
  - search
  - minify:
      minify_html: true

extra:
  # App
  liveBase: https://dariah-beta.dans.knaw.nl
  serverBase: https://github.com/Dans-labs/dariah/blob/master/server
  clientBase: https://github.com/Dans-labs/dariah/blob/master/client
  docsBase: https://github.com/Dans-labs/dariah/blob/master/docs
  staticBase: https://github.com/Dans-labs/dariah/blob/master/static
  modelBase: https://github.com/Dans-labs/dariah/blob/master/server/models
  cssBase: https://github.com/Dans-labs/dariah/blob/master/client/src/css
  appBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/app
  libBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/lib
  testBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/test
  distBase: https://github.com/Dans-labs/dariah/blob/master/static/dist
  repBase: https://github.com/Dans-labs/dariah/blob/master
  repo: https://github.com/Dans-labs/dariah
  docSite: https://dans-labs.github.io/dariah/

  # DARIAH
  dans: https://dans.knaw.nl
  dariah: https://www.dariah.eu
  dariahIDP: https://wiki.de.dariah.eu/display/publicde/DARIAH+AAI+Documentation
  dariahShib: https://wiki.de.dariah.eu/display/publicde/Integrating+Shibboleth+Authentication+into+your+Application

  # TECH
  ale: https://github.com/w0rp/ale
  atom: https://atom.io 
  autovivification: https://en.wikipedia.org/wiki/Autovivification
  babel: https://babeljs.io
  bash: https://www.gnu.org/software/bash/
  beaker: https://beaker.readthedocs.io/en/latest/
  bottle: https://bottlepy.org/docs/dev/
  cloc: https://github.com/AlDanial/cloc
  css: https://developer.mozilla.org/en-US/docs/Web/CSS
  ducks: https://github.com/erikras/ducks-modular-redux
  es7cp: http://borgs.cybrilla.com/tils/es7-class-properties/
  eslint: http://eslint.org
  flake8: https://github.com/PyCQA/flake8
  flask: http://flask.pocoo.org/docs/1.0/
  flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
  geojson: http://geojson.org
  githubBase: https://github.com/
  grid: https://CSS-tricks.com/snippets/CSS/complete-guide-grid/
  hsl: https://en.wikipedia.org/wiki/HSL_and_HSV
  html: https://developer.mozilla.org/en-US/docs/Web/HTML
  ide: https://en.wikipedia.org/wiki/Integrated_development_environment 
  immutability: https://github.com/kolodny/immutability-helper
  iso8601: https://en.wikipedia.org/wiki/ISO_8601
  javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference
  leaflet: http://leafletjs.com
  lodash: https://lodash.com/docs/4.17.15 
  markdownDoc: https://guides.github.com/features/mastering-markdown/
  mern: http://mern.io
  meteor: https://www.meteor.com
  mkdocs: https://github.com/mkdocs/mkdocs
  mkdocsmaterial: https://github.com/squidfunk/mkdocs-material
  mkdocsdans: https://dans-labs.github.io/mkdocs-dans
  mocha: https://mochajs.org
  mongodb: https://docs.mongodb.com
  node: https://nodejs.org
  npm: https://www.npmjs.com
  prettier: https://prettier.io
  python: https://www.python.org
  pythondl: https://www.python.org/downloads
  pythondocs: https://docs.python.org/3/
  react: https://facebook.github.io/react/docs
  reactDocs: https://facebook.github.io/react/docs
  reactRedux: https://react-redux.js.org
  reactReduxRepo: https://github.com/reactjs/react-redux
  reactReselect: https://github.com/reactjs/reselect
  reactRouter: https://github.com/ReactTraining/react-router
  reactRouterApi: https://reacttraining.com/react-router/web/guides/quick-start
  reactRouterTutorial: https://github.com/reactjs/react-router-tutorial/tree/master
  reactSelect: https://github.com/JedWatson/react-select
  remark: https://github.com/remarkjs/remark
  redux: https://redux.js.org
  reduxFormBase: https://redux-form.com
  reduxFormIssues: https://github.com/erikras/redux-form/issues
  reduxFormV: 7.1.2
  reduxVideos: https://egghead.io/courses/getting-started-with-redux
  sassDoc: http://sass-lang.com
  sha: https://www.softwareheritage.org
  shebanq: https://github.com/etcbc/shebanq
  socket: https://socket.io
  socketPython: http://python-socketio.readthedocs.io/en/latest/
  spa: https://en.wikipedia.org/wiki/Single-page_application
  sublimeText: https://www.sublimetext.com
  vim: http://www.vim.org
  vsc: https://code.visualstudio.com
  webApi: https://developer.mozilla.org/en-US/docs/Web/API/document
  webpack: https://webpack.js.org/concepts/
  webstorm: https://www.jetbrains.com/webstorm/
  wsgi: https://modwsgi.readthedocs.io/en/develop
  yapf: https://github.com/google/yapf 
  yaml: http://www.yaml.org
  zenodo: https://zenodo.org

nav:
  - Home: 'index.md'
  - About:
    - Codebase: 'About/Codebase.md'
    - Stats: 'About/Stats.md'
    - News: 'About/News.md'
    - Lessons: 'About/Lessons.md'
    - Diagrams: 'About/Diagrams.md'
  - Functionality:
    - Business: 'Functionality/Business.md'
    - Tables: 'Functionality/Tables.md'
    - Workflow: 'Functionality/Workflow.md'
  - Legacy:
    - Content: 'Legacy/Content.md'
  - Concepts:
    - Architecture: 'Concepts/Architecture.md'
    - Model: 'Concepts/Model.md'
    - Routing: 'Concepts/Routing.md'
  - Server:
    - Authentication: 'Server/Authentication.md'
    - Server: 'Server/Server.md'
  - Client:
    - Components: 'Client/Components.md'
    - Dux: 'Client/Dux.md'
    - Templates: 'Client/Templates.md'
    - Lib: 'Client/Lib.md'
  - Technology:
    - Tech: 'Technology/Tech.md'
    - ES6: 'Technology/ES6.md'
    - React: 'Technology/React.md'
  - Integration:
    - API: 'Integration/API.md'
  - Maintenance:
    - Deploy: 'Maintenance/Deploy.md'
    - Tests: 'Maintenance/Tests.md'
