import React from 'react'

import ContribItem from 'ContribItem.jsx';

/**
 * @module ContribItemPre
 */

/**
 * **purely functional** {@link external:Component|Component}
 *
 * Prepare the way to load an item view of a contribution.
 * Needed when you want to navigate to a specific contribution
 * by means of the Router.
 *
 * @class
 * @param {Object} params The parameters generated by the 
 * @returns {Fragment}
 */
const ContribItemPre = ({ params, route }) => {
  const cId = params.contribId;
  const own = route.ownOnly;
  return (<ContribItem tag={`contrib_${cId}`} contribId={cId} ownOnly={own}/>)
}

export default ContribItemPre
