import React from 'react'

/**
 * @module ContribItemNew
 */

/**
 * **purely functional** {@link external:Component|Component}
 *
 * Displays a control to add a new contribution record.
 *
 * @class
 * @param {Object} params The parameters generated by the 
 * @returns {Fragment}
 */

const ContribNew = ({ insertRow }) => (
  <a
    className="button fa fa-plus"
    href="#"
    title="New contribution"
    onClick={insertRow}
  > new ...</a>
)
export default ContribNew


