import React from 'react'

import ItemRecord from 'ItemRecord.jsx';

/**
 * @module ItemRecordPre
 */

/**
 * **purely functional** {@link external:Component|Component}
 *
 * Prepare the way to load an item view of an item.
 * Needed when you want to navigate to a specific item
 * by means of the Router.
 *
 * @class
 * @param {Object} params The parameters generated by the 
 * @returns {Fragment}
 */
const ItemRecordPre = ({ params, route }) => {
  const { tag, recordId } = params;
  const { ownOnly } = route;
  return (<ItemRecord tag={`${tag}_${recordId}`} table={tag} recordId={recordId} ownOnly={ownOnly}/>)
}

export default ItemRecordPre
