staticRoot: ../static/
secretFile: /opt/web-apps/dariah_jwt.secret
shibKey: Shib-Session-ID
creator: HaSProject

attributes:
  o: org
  cn: name
  givenName: firstName
  sn: lastName
  isMemberOf: membership
  affiliation: rel

names:
  - DARIAH
  - devel
  - eppn
  - group
  - groupRep
  - Guest
  - isEdit
  - isOur
  - isOwn
  - isPristine
  - local
  - mail
  - modified
  - name
  - No
  - number
  - org
  - REGIME
  - read
  - record
  - related
  - sameCountry
  - text
  - unknown
  - Yes
