title: Tech Doc DARIAH contribution tool
tagline: Building in-kinds
email: dirk.roorda@dans.knaw.nl
description: > 
  The technical design of the DARIAH Contribution Tool.

baseurl: /dariah
logo: /images/inkind_logo.png

url: "https://dariah-beta.dans.knaw.nl/" 
github_username:  Dans-labs

staff:
    - name: Dirk Roorda
      email: dirk.roorda@dans.knaw.nl
      hide: false
      institute: DANS
      url: https://dans.knaw.nl/nl

repos:
    - name: dariah
      url: https://github.com/Dans-labs/dariah
      desc: DARIAH contribution tool

web:
    name: DARIAH contribution tool
    url: https://dariah-beta.dans.knaw.nl/
    desc: Registry of DARIAH inkind-contributions, with assessments and reviews.

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# App
liveBase: https://dariah-beta.dans.knaw.nl
serverBase: https://github.com/Dans-labs/dariah/blob/master/server
clientBase: https://github.com/Dans-labs/dariah/blob/master/client
staticBase: https://github.com/Dans-labs/dariah/blob/master/static
cssBase: https://github.com/Dans-labs/dariah/blob/master/client/src/css
appBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/app
libBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/lib
testBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/test
repBase: https://github.com/Dans-labs/dariah/blob/master
repo: https://github.com/Dans-labs/dariah
docSite: https://dans-labs.github.io/dariah/

# DARIAH
dans: https://dans.knaw.nl
dariah: https://www.dariah.eu
dariahIDP: https://wiki.de.dariah.eu/display/publicde/DARIAH+AAI+Documentation
dariahShib: https://wiki.de.dariah.eu/display/publicde/Integrating+Shibboleth+Authentication+into+your+Application

# TECH
autovivification: https://en.wikipedia.org/wiki/Autovivification
babel: https://babeljs.io
bash: https://www.gnu.org/software/bash/
beaker: https://beaker.readthedocs.io/en/latest/
bottle: https://bottlepy.org/docs/dev/
cloc: https://github.com/AlDanial/cloc
css: https://developer.mozilla.org/en-US/docs/Web/CSS
ducks: https://github.com/erikras/ducks-modular-redux
es7cp: http://borgs.cybrilla.com/tils/es7-class-properties/
eslint: http://eslint.org
flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
geojson: http://geojson.org
grid: https://CSS-tricks.com/snippets/CSS/complete-guide-grid/
hsl: https://en.wikipedia.org/wiki/HSL_and_HSV
html: https://developer.mozilla.org/en-US/docs/Web/HTML
immutability: https://github.com/kolodny/immutability-helper
iso8601: https://en.wikipedia.org/wiki/ISO_8601
javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference
leaflet: http://leafletjs.com
lodash: https://lodash.com/docs 
markdownDoc: https://guides.github.com/features/mastering-markdown/
mern: http://mern.io
meteor: https://www.meteor.com
mocha: https://mochajs.org
mongodb: https://docs.mongodb.com
node: https://nodejs.org
npm: https://www.npmjs.com
prettier: https://prettier.io
python: https://docs.python.org/3/
reactDocs: https://facebook.github.io/react/docs
reactReselect: https://github.com/reactjs/reselect
redux: http://redux.js.org
reduxFormBase: https://redux-form.com
reduxFormIssues: https://github.com/erikras/redux-form/issues
reduxFormV: 7.1.2
reduxVideos: https://egghead.io/courses/getting-started-with-redux
reactRedux: https://github.com/reactjs/react-redux/blob/master
reactRouter: https://github.com/ReactTraining/react-router/blob/v3/docs
reactRouterTutorial: https://github.com/reactjs/react-router-tutorial/tree/master
reactSelect: https://github.com/JedWatson/react-select
sassDoc: http://sass-lang.com
shebanq: https://github.com/etcbc/shebanq
spa: https://en.wikipedia.org/wiki/Single-page_application
webApi: https://developer.mozilla.org/en-US/docs/Web/API/document
webpack: https://webpack.js.org/concepts/
wsgi: https://modwsgi.readthedocs.io/en/develop
yaml: http://www.yaml.org
