title: Tech Doc DARIAH contribution tool
tagline: Building in-kinds
email: dirk.roorda@dans.knaw.nl
description: > 
  The technical design of the DARIAH Contribution Tool.

baseurl: /dariah
logo: /images/inkind_logo.png

url: "https://dariah-beta.dans.knaw.nl/" 
github_username:  dirkroorda

staff:
    - name: Dirk Roorda
      email: dirk.roorda@dans.knaw.nl
      hide: false
      institute: DANS
      url: https://dans.knaw.nl/nl

repos:
    - name: dariah
      url: https://github.com/Dans-labs/dariah
      desc: DARIAH contribution tool

web:
    name: DARIAH contribution tool
    url: https://dariah-beta.dans.knaw.nl/
    desc: Registry of DARIAH inkind-contributions, with assessments and reviews.

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

liveBase: https://dariah-beta.dans.knaw.nl
serverBase: https://github.com/Dans-labs/dariah/blob/master/server
clientBase: https://github.com/Dans-labs/dariah/blob/master/client
appBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/app
libBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/lib
testBase: https://github.com/Dans-labs/dariah/blob/master/client/src/js/test
repBase: https://github.com/Dans-labs/dariah/blob/master
